```text
graph TD
    A[User] --> U1(Login)
    A --> U2(Create Account)

    U2 --> U1

    U1 --> U3(Research Stock)
    U1 --> U8(Manage Portfolio)

    U3 --> U4(Get EOD Price)
    U3 --> U5(Get Quote)
    U3 --> U6(Buy Stock)
    U3 --> U7(What-If Position)

    U8 --> U9(Sell Stock)
    U8 --> U10(Remove Stock)
    U8 --> U11(Review Transaction Log)
```